# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }

swiftmailer:
    transport: smtp
    auth_mode: login
    port: 587
    host: ssl0.ovh.net
    username: contact@mao-bd.com
    password: ContactMao-bd
    spool: { type: 'memory' }